### ISSUE TITLE
export_TextGridCollection() fails on ITEM without links to SEGMENT

### ISSUE THREAD

**Issue by florianschiel** [IPS-LMU/emuR#119]
export_TextGridCollection() stops when finding a bundle in which an ITEM level contains an item without any links to a level of type SEGMENT, that is a 'free-floating' item for which no timing information can be deducted; such items are allowed in the emuDB and appear with 'NA' times in query results, such as:

```
           labels       start         end session  bundle level type
```

1                 tu        NA        NA SES0155 sent007  Word ITEM
2               obok  2210.03125  2570.03125 SES0155 sent007  Word ITEM
3           czterech  2570.03125  2970.03125 SES0155 sent007  Word ITEM

A sensible way to deal with this could be to skip such items in the Textgrid output.

**Comment by raphywink** [comment]
`export_TextGridCollection()` can deal with orphan ITEMS (because this issue is quite old I think I just 4got to close it). I just created this orphan ITEM on the Phoneme level:

![screen shot 2018-03-26 at 18 26 18](https://user-images.githubusercontent.com/435436/37919257-b064134e-3123-11e8-93c4-d9e45e79ed80.png)

and after `export_TextGridCollection()` I get the expected resutl:

![screen shot 2018-03-26 at 18 28 37](https://user-images.githubusercontent.com/435436/37919286-c2465cc0-3123-11e8-9ea0-486d16c86f13.png)

Which is a missing segment (the orphan segment was ignored by the export routine)
