### ISSUE TITLE
level names vs. attrDefs

### ISSUE THREAD

**Issue by raphywink** [IPS-LMU/emuR#120]
When querying an attribute definition:

``` R
query(ae, "Text =~ .*")[1,]
```

we list the requested attribute definition as the `level` in the emuRsegs object:

``` R
segment  list from database:  ae 
query was:  Text =~ .* 
   labels start     end session   bundle level type
1 amongst     0 674.175    0000 msajc003  Text ITEM
```

This is probably due to backwards compatibility. So my question is (@florianschiel, @klausj): shouldn't we be returning the actual level name in the level column of the emuRsegs object and maybe expand the emuRsegs object to include a column called attrDef that tells the user what attribute definition the item is from? Wouldn't that be a cleaner way of doing things?

**Comment by florianschiel** [comment]
The answer depends very much on how the (legacy Emu) functions in emuR 
rely on this column.
 From the user perspective the difference between level and attribute is 
not very transparent, since both can be used inter-changeably in queries.
So, I'd guess that the average user expects the attribute name here and 
would be surprised to find a different name as she/he used in the query.

Flo
