### ISSUE TITLE
Bundle names with utf-8 characters

### ISSUE THREAD

**Issue by danijel3** [IPS-LMU/emuR#158]
Although they display fine with list_bundles, all bundles with non-ascii characters seem to be ignored by the query function.

To reproduce the bug, I looked for a particular word that exists in all bundles, but the output list will always contain only those bundles whose names are ascii characters.

I assume the same problem is probably the same with session names, but haven't tested it.

**Comment by raphywink** [comment]
Oh dear... that's no good! Just to clarify: what OS are you running? It would really really surprise me if you are the first one to notice this on a Unix based machine (most EMU users tend to be on Macs or Linux). Windows + R + UTF-8 + SQLITE is an absolute nightmare... you basically have to set every string as "binary" so that there is no "magic" re-encoding going on. Could be that we overlooked that some place...

**Comment by danijel3** [comment]
I'm on Linux, Debian to be precise. I didn't expect this to be an OS issue, so I just copied the DB to windows and it works fine there!

Not sure if it helps, but on Debian I have this version:
R version 3.3.3 (2017-03-06) -- "Another Canoe"
And on windows:
R version 3.4.1 (2017-06-30) -- "Single Candle"

The libraries for Debian are:
RSQLite 1.0.0
DBI 0.5-1
And on Windows:
RSQLite 2.0.0
DBI 0.7

You think I should update the libraries on Linux?

**Comment by raphywink** [comment]
Ok strange... just tested the following on my OSX 10.12.6 machine and on a Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-125-generic x86_64) machine:

added the UTF-8 symbols ⺐ and 😁  to make a bundle called: msajc003⺐😁_bndl

emuDB is here: [ae_emuDB.zip](https://github.com/IPS-LMU/emuR/files/1299878/ae_emuDB.zip)
:

```r
list_bundles(ae)
```

gives me
```
  session                 name
1    0000 msajc003⺐\U0001f601
2    0000             msajc010
3    0000             msajc012
4    0000             msajc015
5    0000             msajc022
6    0000             msajc023
7    0000             msajc057
```

and

```r
query(ae, "Phonetic == n")
```
gives me

```
segment  list from database:  ae 
query was:  Phonetic == n 
   labels    start      end session               bundle    level    type
1       n 1031.925 1195.925    0000 msajc003⺐\U0001f601 Phonetic SEGMENT
2       n 1741.425 1791.425    0000 msajc003⺐\U0001f601 Phonetic SEGMENT
3       n 1515.475 1554.475    0000             msajc010 Phonetic SEGMENT
4       n 2430.975 2528.475    0000             msajc010 Phonetic SEGMENT
5       n  894.975 1022.975    0000             msajc012 Phonetic SEGMENT
6       n 2402.275 2474.875    0000             msajc012 Phonetic SEGMENT
7       n 2226.575 2271.075    0000             msajc015 Phonetic SEGMENT
8       n 3046.125 3067.675    0000             msajc015 Phonetic SEGMENT
9       n 1434.775 1495.275    0000             msajc023 Phonetic SEGMENT
10      n 1774.925 1833.925    0000             msajc023 Phonetic SEGMENT
11      n  508.675  543.975    0000             msajc057 Phonetic SEGMENT
12      n 2447.675 2480.425    0000             msajc057 Phonetic SEGMENT
```

what does `devtools::session_info()` give you? Might be due to a collate setting...

**Comment by danijel3** [comment]
I just made a new test database and couldn't reproduce the error. Then I went back to the old one and it stil didn't work. So I ended up deleting the SQLITE database file and reloading the database and now it works :(

Seems like a false alarm after all. Sorry for wasting your time!

**Comment by danijel3** [comment]
If anyone else ends up here, here's the lines from session_info - the collation was fine after all:

 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language en_US:en                    
 collate  en_US.UTF-8                 
 tz       Poland                      
 date     2017-09-13
