### ISSUE TITLE
What is the preferred method of handling of outside code related to this project?

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/emuR#169]
Hi,

I applaud your ambitious approach here and really think that the LMU group is doing yours to bring speech science into a state where we got the tools that we need to do larger studies more efficiently. Now, here is my problem - and the related question:

Like most people, I think, that primarily use R for data processing, I have developed my own package of functions that are generally quite useful for speech science. Now, I see that I have two options - 1) I can continue developing this separate package and then just don't care about trying to make the world a better and more consistent place, or 2) I could start gearing my functions towards working well with the emuR package. 

Nr 2 is of course preferable for the sake of mankind ;-) but with a book also being produced, which I have not seen, then I feel that me sending you patches to you may just interfere with your work. An alternative approach, which is what we see in the "tidyverse" group of packages, is that the core package is left as it is and others just relate to it and make sure that they work well together.  I am currently thinking that this is the best option, since I then would not be adding to the already diverse package of legacy functions, your new functions and my new functions - all with the structure and conventions of the time when they were written. However, I would like to ask you what the project group would prefer us to do, as outsiders. In my humble opinon, speech science is really not helped by the diversity of tools and structures. It is like we are trying to kill ourselves by applying the old military tactic of "divide and conquer" on our own discipline (and I don't know then who should do the conquering). So, please tell me how we should relate to your project.

**Comment by raphywink** [comment]
This is generally a really difficult question to answer / problem to discuss. I do think that one of the guiding principals in developing a multi-package ecosystem has to be separation of concerns. For example: wrassp does signal processing and emuR doesn't and shouldn't (I am aware that this line is sometimes blurred by some legacy emu code). However, emuR uses wrassp extensively to do signal processing. In my opinion, if you where to implement some signal processing routines, they would best be implemented in an additional package that has a similar API to the wrassp wrapper functions, so that emuR can call these methods in a similar way (hence only needing slight modifications in the emuR code). Same goes for things such as visualization routines and statistical methods/analysis (that for example take a emuRtrackdata object as their input). However, I do think that there is a place for expanding the emuR package itself. If you want to, for example implement something like a "somehow change the emuDB configuration" function (like add_levelDefinition()) we should definitely discuss if that might be better suited to be a part of the emuR package. However, we should always consider that emuR should only contain functions that scale to multiple types of problems/databases. A function that is only useful for a special use-case and does not generalize to other problems should probably be placed elsewhere... 

I think the general focus of the emuR package should be:

- generate and configure emuDBs
- serve emuDBs to the EMU-webApp
- extract items/segments/events as emuRsegs lists (== data.frame like object)
- extract signals/tracks that belong to an emuRsegs object in the form of an emuRtrackdata object (== data.frame like object)
- maybe offer some general purpose emuRtrackdata manipulation like https://github.com/IPS-LMU/emuR/blob/master/R/emuR-emuRtrackdata.R#L88

everything else should be handled elsewhere. For example, we are currently comprising dplyr and ggplot2 commands that implement the same features as eplot(), dplot() and dcut(). These will not be part of the emuR package but instead most likely part of a future version the EMU-SDMS manual (yet to be released) in the form of recipes that basically let users look for "you want a plot that looks like this... then do this: ...".

**Comment by dargosch** [comment]
Sure, I understand the difficulty in answering the question in a general way, but I think you did a good job. What I was kind of thinking about was core functionality and departing from the way of thinking that formed the basis for previous versions of the library. eplot, dplot and dcut are great examples of what I mean. I guess the answer should maybe most often be "make your own package".
