### ISSUE TITLE
The naming of functions should be better aligned with  R conventions 

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [IPS-LMU/emuR#199]
This will seriously mess with users' scripts, but the emu R package currently has some unorthodox naming of functions that is confusing for an R user. After now more years of R use than I care to admit, I usually don't have a problem understanding a new package, but emuR is confusing. And some of the issues are in legacy functions that I don't know if they will stay in the package going forward.. But, here goes:

  - convert_* . Are these functions not really import functions for the user? Sure, the developer will have to make sure that there is a conversion being done, but I just want to import the data. And, when you want to get data out of the system in an external format you use "export_*" functions, so getting data into the system from an external format should be "import" I think.

- buildtrack is really trackdata applied to list data, so in S3 I think it should be trackdata.by() if you want to keep the by function and class (see discussion below).

- makelab and make.seglist, make.emuRsegs, ...  These are a confusing. Makelab I think perhaps should be removed from the package, or made into a export_ function. make.emuRsegs is a constructor for segments objects, and should be named just "segments" IMHO if that is an acceptable name for the class. And maybe this is not a function then that should be put out there for the user to be confused by, as segments objects are primarilly constructed by calling query right? Or reading from a file I guess, using a special read_segments function perhaps? 
If someone wants to do fancy stuff with manual creation of segments objects, then you can always access not exported functions as emuR:::segments. 

- Apply functions are named in base R by what they output. `lapply` returns a list, `sapply` simplified version of the output of lapply, an so on. So, therefore the *apply functions in the emuR package are a bit confusingly named. For instance, both `trapply`and `dapply` returns track objects (or trackdata objects then in the current terminology). Its confusing to know which one to use when from the name, and even more confusing that `trapply`does not have to return a track object but `dapply` always has to even though it is not named that way. 

- dsmooth, ddiff : unfortunately diff is a generic function in R, but smooth is not. So, you could have a diff.track(data) function that then fits nicely into R S3 calling and then also tells the user something about what the function should be given as an argument. `dsmooth` is more tricky, but since "data" is not very informative, "trsmooth" would be a clarification.

I realize of course that the emuR package is in a transition phase, but the dual class structures sometimes creates some odd situations in the docs:

> segment  emuR segment list
> segmentlist | Segment list

So, segment is a list, but segmentlist is a list of segments (which was a list..?). And there is "emuRsegs" which is documented as a separate thing, but is not really right? And the "list" entry in the docs..
I suggest a simple "segments" class. It makes it clear that it is usually a set of many segments.

I see that for instance "emuRsegs" is a way to separate new classes from the old structures in the same package. But, it is a bit odd since the user already know that he/she is using the emuR package, and since this naming convention is carried over to the docs too. The same goes of course for emuRtrackdata. 

Actually, trackdata is an old issue. It s very often referred to in the docs of functions  manipulating them as a "track", which is what these objects are actually. The "data" part of the name is superfluous (what else do we store in objects?) and potentially confusing going forward.

**Comment by raphywink** [comment]
Because I am pressed for time I will try to keep this short: most if not all S3 class functions will become depricated over the short or the long term. The workflow is/will be:

1. load_emuDB() -> datahandle object (will probably remain S3)
2. query database -> returns a tibble object containing query result
3. use output of 2. to get_trackdata which outputs a tibble object again containing the combind information of 2. and 3.

The output of 3 can then be used by the user to do whatever they want (just go nuts using dplyr / ggplot2 / ... we have been able to replicate all of the behaviour of the S3 functions using such packages... these examples will be added to the manual in the not so distant future e.g. eplot with ggplot2 etc.). The old S3 methods will probably remain in the emuR package for backward compatability.  Using the resulttype='tibble' parameter in get_trackdata() 3. is already possible.

@import vs convert: we convert a textgrid collection to a emuDB. We import for example media files into an emuDB. So I disagree...

**Comment by raphywink** [comment]
Just regarding my "keeping the S3 for backward compatibility". EMU, in some form, has been around for over 25 years now... so there is quite a history there and there are also a lot scripts around that we would otherwise break completely. Keeping the legacy objects in place allows for those to be reproduced...

**Comment by FredrikKarlssonSpeech** [comment]
Sounds like a nice plan. I would actually love to see the pruning of functions to happen sooner rather than later, so we as users may start thinking about how to use them for our purposes.

The old classes and functions will be marked as deprecated soon-ish I guess then, so people get a heads up of the change?

regarding import and convert - well I guess it depends on how you look at things. And the current scheme is perhaps the most obvious for others. I just feel that it is strange to have a situation where I perhaps "export" transcriptions to get them out of Emu to say TextGrids that may have actually been TextGrid files to begin with, but when getting  I did not get them into Emu by "import":ing them. 

"Convert" has no sense of direction, so you get the information actually implicitly from the fact that you are talking about Emu after all, and the fact that the second part of the function name implies an external format.  "export" and "import" makes the direction clear.

But, as they say "Not my circus, not my monkeys", so please disregard this opinion if you still think it is the best way forward.
