### ISSUE TITLE
Error in result_create(conn@ptr, statement) : too many SQL variables

### ISSUE THREAD

**Issue by PeterGilles** [IPS-LMU/emuR#206]
I have an imported set of TextGrids ~1300), which I queried with

```sibil = query(frech,"utterance/phon =~ '[szSZ]'")```

resulting in the following object:

```segment  list from database:  frech 
query was:  utterance/phon =~ ''[szSZ]'' 
  labels     start        end session           bundle          level    type
1      z    0.0000  100.21542    0000 pg_69_1000_aje71 utterance/phon SEGMENT
2      z  587.8345  638.83220    0000 pg_69_1000_aje71 utterance/phon SEGMENT
...
```

When running `get_trackdata` I am getting the error below:

```
dftTd = get_trackdata(frech,
+                       seglist = sibil,
+                       onTheFlyFunctionName = 'dftSpectrum', verbose=T)

  INFO: applying dftSpectrum to 2622 files
  |                                                                                 |   0%
Error in result_create(conn@ptr, statement) : too many SQL variables
```

**Comment by raphywink** [comment]
Two people discovering the same bug within 24 hours :-)... that doesn't happen very often ;-) (the other was reported to me via Email... so no way you could have known). Unfortunately this is due to an internal parameter of SQLite (SQLITE_MAX_VARIABLE_NUMBER) which is set to 999 and can't be overwritten (unless you change the source code and recompile). I will have to have a look at get_trackdata() to see if I can recode it to not use an SQLite temp table. As a quick work around you could reduce the number of columns returned by `dftSpectrum` by increasing the frequency resolution:

```r
db = load_emuDB("~/Desktop/gassed_rat_emuDB")
fric.s = query(db, query="phonetic == s") 

params = formals(wrassp::dftSpectrum)
```

params$resolution = 80 # default is 40 Hz which gives you 1024 values (> SQLITE_MAX_VARIABLE_NUMBER=999) -> 80 will give you 512

```r
tr = get_trackdata(emuDBhandle = db, 
                  ssffTrackName="dft",
                  seglist=fric.s[2,],
                  onTheFlyFunctionName="dftSpectrum",
                  onTheFlyParams = params,
                  resultType = "tibble”)
```

Will try to fix this asap though...

**Comment by PeterGilles** [comment]
Thank you for your fast reply. Es funktioniert.
