### ISSUE TITLE
import TextGrid files in a way similar to import_mediaFiles()

### ISSUE THREAD

**Issue by vdca** [IPS-LMU/emuR#235]
At the moment, one can use convert_TextGridCollection() to create an emuDB. This works great, but afaik it is not possible to add TextGrid collections to an existing emuDB. It seems to me that adding this flexibility would be very useful. Two thoughts on how to approach this:

- create a new function import_TextGrids(), mirroring the import_mediaFiles() function.
- tweak the convert_TextGridCollection() function so that it does not fail when the targetDir/dbName exists, but rather enables the creation of new sessions. This could work well with the possibility of having a recursive=F argument, together with an explicit targetSessionName argument.

**Comment by raphywink** [comment]
Although I see that this would be a nice to have feature, unfortunately this will be extremely difficult and very time consuming to achieve/implement as the annotation structure of emuDBs can be quite complex (see for example Figure 4.2: B here: https://ips-lmu.github.io/The-EMU-SDMS-Manual/chap-annot-struct-mod.html#per-database-annotation-structure-definition) and one would have to try to map the set of TextGrids tiers to those annotation structures. Unfortunately I don't see me having the time to implement this any time soon. The current workflow for adding new files TextGrids to an existing emuDB that I recommend is the following:

- convert the new TextGrids to a completely new emuDB using `convert_TextGridCollection()`
- use `autobuild_linkFromTimes()` create the exact same annotation structure as the existing emuDB
- move the bundles/session of the new emuDB into the old one using the file explorer of your choice or script it using R
- reload the old emuDB now containing the new bundles so that emuR detects the changes
