### ISSUE TITLE
Formant correction tool bug

### ISSUE THREAD

**Issue by josh-penn** [IPS-LMU/emuR#236]
When using the formant correction tool the point that becomes active and is changed is 7-8 points to the right of where my cursor is placed, which makes accurate corrections quite difficult. I've tried this on multiple devices and experience the same issue on all of them.  

Is there perhaps a workaround?

I'm using version 2.1.0 with Chrome Version 85.0.4183.83.

**Comment by raphywink** [comment]
This had to do with an outdated faulty version of this function: https://raw.githubusercontent.com/IPS-LMU/The-EMU-SDMS-Manual/master/R/praatToFormants2AsspDataObj.R which is described here: https://ips-lmu.github.io/The-EMU-SDMS-Manual/app-chap-wrassp.html#sec:app-chap-wrassp-praatsSigProc Issue was fixed by using the new version.
